apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-aiops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-aiops
  template:
    metadata:
      labels:
        app: java-aiops
    spec:
      containers:
      - name: app
        image: "{{ .Values.image }}"
        ports:
        - containerPort: 8080
